on:
  repository_dispatch:
    types: dalonega-dev-deployment
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.jitudevops.com
          username: dahlonegakey@dahlonegagroup.jitudevops.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.DEV_SERVER }}
          port: 21
          protocol: ftp  # Use regular FTP instead of FTPS
          security: loose  # Add this to handle certificate issues

      - name: Syncing Report
        run: |
          echo "Starting FTP sync..."
          echo "Using server: ftp.jitudevops.com"
          echo "Using directory: ${{ secrets.DEV_SERVER }}"
          echo "Syncing files..."
          echo "FTP sync completed successfully."
      
      - name: Report Progress
        run: |
          echo "Progress: 10%"
          # Run your deployment steps here
          echo "Progress: 50%"
          # Continue with deployment
          echo "Progress: 100%"
