on:
  repository_dispatch:
    types: dalonega-dev-deployment
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 68.65.120.172
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.DEV_SERVER }}
          timeout: 60
      - name: Report Progress
        run: |
          echo "Progress: 10%"
          # Run your deployment steps here
          echo "Progress: 50%"
          # Continue with deployment
          echo "Progress: 100%"
